// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuIKpvrZgrrqFBLsgr21SxbTCnIyXrIo',
    appId: '1:1080317807087:web:bfffcc00df508344e7ce1a',
    messagingSenderId: '1080317807087',
    projectId: 'todosmart-c28d5',
    authDomain: 'todosmart-c28d5.firebaseapp.com',
    databaseURL: 'https://todosmart-c28d5-default-rtdb.firebaseio.com',
    storageBucket: 'todosmart-c28d5.appspot.com',
    measurementId: 'G-HCNCZL3QXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUC4vV8aQKd4R4O3iyvWAa-vYTepgY1Ww',
    appId: '1:1080317807087:android:d733cfe9300b850fe7ce1a',
    messagingSenderId: '1080317807087',
    projectId: 'todosmart-c28d5',
    databaseURL: 'https://todosmart-c28d5-default-rtdb.firebaseio.com',
    storageBucket: 'todosmart-c28d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnNMOjI5TBWr0sa69ozasoyhPCJEw2ous',
    appId: '1:1080317807087:ios:95da32f2b7cad737e7ce1a',
    messagingSenderId: '1080317807087',
    projectId: 'todosmart-c28d5',
    databaseURL: 'https://todosmart-c28d5-default-rtdb.firebaseio.com',
    storageBucket: 'todosmart-c28d5.appspot.com',
    iosClientId:
        '1080317807087-0g52nlpda2dccu4vb88np6bkj8kust4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnNMOjI5TBWr0sa69ozasoyhPCJEw2ous',
    appId: '1:1080317807087:ios:95da32f2b7cad737e7ce1a',
    messagingSenderId: '1080317807087',
    projectId: 'todosmart-c28d5',
    databaseURL: 'https://todosmart-c28d5-default-rtdb.firebaseio.com',
    storageBucket: 'todosmart-c28d5.appspot.com',
    iosClientId:
        '1080317807087-0g52nlpda2dccu4vb88np6bkj8kust4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartApp',
  );
}
