name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.12'
    - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-build
        path: build/app/outputs/apk/release

  build_web:
    name: Build and Deploy (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODOSMART_C28D5 }}'
          channelId: live
          projectId: todosmart-c28d5
